### ISSUE TITLE
Token with Customer ID

### ISSUE THREAD

**Issue by ktre2017** [Taracque/cordova-plugin-braintree#37]
Can we use this plugin to pass CustomerID and get ClientToken to retrieve saved card details depends on CustomerID?

Please advise.

**Comment by antkers** [comment]
You should never generate a specific client token on the client side because you would need to ship out your very personal merchantId, publicKey and privatekey in your client app.
Generate it on your server side e.g. web service instead and retrieve through a secure http get call in your client.
Here's the code and documentation from braintree if you use a node.js (drop down on top for other programming languages) server: https://developers.braintreepayments.com/start/hello-server/node#generate-a-client-token
Hope that helps you!
